### ISSUE TITLE
Add timeline

### ISSUE THREAD

**Issue by holubkova** [alieninochi/homepage#6]

**Comment by alien-inochi** [comment]
2006
The search for Spencer, owner of the Umbrella corporation
2005
Found a virus called T-Abyss and neutralized the terrorists on the ship Queen Dido
2004
Became a Bioterrorism Security Assessment Alliance agent o fight the legacy of the Umbrella corporation
2003
Investigation of Umbrella's secret base in Russia and liquidation of the corporation
1999
Investigation of the Raccoon City incident that turned residents into zombies
1998
Investigation of a series of mysterious murders in Raccoon City; detection of the t-virus and the association of the Umbrella corporation with it
1996
Was was recruited by Albert Wesker for the Special Tactics and Rescue Service (S.T.A.R.S.), an elite unit of Raccoon Police Department (RPD)
1992
Completed a six-month intensive course led by the Delta Force
Early 90s
Served in the US Army
