### ISSUE TITLE
Add additional information

### ISSUE THREAD

**Issue by holubkova** [alieninochi/homepage#7]

**Comment by alien-inochi** [comment]
Personality: 

Numerous official documents, highlight Jill's unrivalled ability to remain calm under extreme conditions, her quick thinking has kept herself and her comrades alive on numerous occasions. Jill cheerful yet determined, with a strong sense of justice, while her involvement with S.T.A.R.S., a BioHazard Containment Unit as well as a co-founding high ranking role within the BSAA show her years of commitment to stopping bioterror and fighting for peace and the protection of innocents.

**Comment by alien-inochi** [comment]
Jill's infographics:
100232 - zombie killed
21034902 - lives saved
1 - corporations of evil liquidated
366 - sandwiches eaten
